<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Statistics: Final Report</title>

<script src="site_libs/header-attrs-2.14/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Ecology BIO 239 Laboratory</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="spring2022.html">Spring 2022</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Statistics: Final Report</h1>

</div>


<div style="margin-bottom:50px;">
<p>Download the package <code>tidyverse</code></p>
</div>
<div style="margin-bottom:50px;">
<table>
<thead>
<tr class="header">
<th align="left">insect</th>
<th align="right">east_fall</th>
<th align="right">east_spring</th>
<th align="right">north_fall</th>
<th align="right">north_spring</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">carolina</td>
<td align="right">17</td>
<td align="right">0</td>
<td align="right">59</td>
<td align="right">4</td>
</tr>
<tr class="even">
<td align="left">green_striped</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
<td align="right">61</td>
</tr>
<tr class="odd">
<td align="left">katydid</td>
<td align="right">18</td>
<td align="right">1</td>
<td align="right">13</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">mantis</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">red_legged</td>
<td align="right">47</td>
<td align="right">0</td>
<td align="right">75</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
</div>
<div style="margin-bottom:50px;">
<pre class="r"><code>data3 &lt;- read.csv(&quot;bio239_spring2022b.csv&quot;)
data3</code></pre>
<pre><code>##          species season mound count
## 1       carolina   fall  east    17
## 2  green_striped   fall  east     0
## 3        katydid   fall  east    18
## 4         mantis   fall  east     6
## 5     red_legged   fall  east    47
## 6       carolina spring  east     0
## 7  green_striped spring  east     7
## 8        katydid spring  east     1
## 9         mantis spring  east     0
## 10    red_legged spring  east     0
## 11      carolina   fall north    59
## 12 green_striped   fall north     0
## 13       katydid   fall north    13
## 14        mantis   fall north     1
## 15    red_legged   fall north    75
## 16      carolina spring north     4
## 17 green_striped spring north    61
## 18       katydid spring north     0
## 19        mantis spring north     0
## 20    red_legged spring north     0</code></pre>
</div>
<div style="margin-bottom:50px;">
<pre class="r"><code>data3 &lt;- as_tibble(data3)
data3</code></pre>
<pre><code>## # A tibble: 20 x 4
##    species       season mound count
##    &lt;chr&gt;         &lt;chr&gt;  &lt;chr&gt; &lt;int&gt;
##  1 carolina      fall   east     17
##  2 green_striped fall   east      0
##  3 katydid       fall   east     18
##  4 mantis        fall   east      6
##  5 red_legged    fall   east     47
##  6 carolina      spring east      0
##  7 green_striped spring east      7
##  8 katydid       spring east      1
##  9 mantis        spring east      0
## 10 red_legged    spring east      0
## 11 carolina      fall   north    59
## 12 green_striped fall   north     0
## 13 katydid       fall   north    13
## 14 mantis        fall   north     1
## 15 red_legged    fall   north    75
## 16 carolina      spring north     4
## 17 green_striped spring north    61
## 18 katydid       spring north     0
## 19 mantis        spring north     0
## 20 red_legged    spring north     0</code></pre>
</div>
<div style="margin-bottom:50px;">
<p>The starting model contains, as its predictors, the main effect of the response factor (in our study, the species of insect at a site, or mound) and the main effects and and mutual interactions of th explanatory factors. The response variable in this model is the counts. We set up the null model (with a Poisson distribution and an implicit log link function) as follows:</p>
</div>
<div style="margin-bottom:50px;">
<pre class="r"><code>glm.x0 &lt;- glm( count ~ species + season * mound, data = data3, family = poisson)</code></pre>
</div>
<div style="margin-bottom:50px;">
<p>We compare this model with alternative models, each extended by one of the two interactions between the response factor (species) and an explanatory factor:</p>
</div>
<div style="margin-bottom:50px;">
<pre class="r"><code>add1 ( glm.x0, scope = ~species * season * mound, test = &quot;Chisq&quot;)</code></pre>
<pre><code>## Single term additions
## 
## Model:
## count ~ species + season * mound
##                Df Deviance    AIC    LRT  Pr(&gt;Chi)    
## &lt;none&gt;              322.99 391.27                     
## species:season  4    25.78 102.06 297.21 &lt; 2.2e-16 ***
## species:mound   4   279.51 355.79  43.48 8.225e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div style="margin-bottom:50px;">
<p>We use the <code>scope</code> parameter to specify the target model with a full interaction among all three factors for the <code>add1</code> function, but the function has its own rules regarding the sequence of testing interactions of different orders. Consequently, the test of the second-order interaction (i.e., the “species:season:mound” term) is omitted here, as well as the “season:mound” interaction term, which is already present in the null model.</p>
<p>Both tested interactions have a significant effect (p &lt; 0.001) and explain a relatively large fraction of the variability that was not explained by the null model. (See the Deviance column: e.g., species:season term explains (100 x (322.99 - 25.78)/322.99) = XX.XX%) of the variation unexplained by the glm.x0 model.)</p>
<p>The tests are based on X^2 (Chi-Square) statistics (due to a specific test parameter in the add1 function call) but in the add1 output this statistic is labelled LRT (likelihood ratio test), which it indeed represents.</p>
<p>We also not that the <code>add1</code> function scores the 3 models under comparison with the information-theoretic statistic (AIC) value and this comparison confirms the appropriateness of adding both interactions to the model. The effect of the mound type seems to be larger than the season, which is in agreement with the likelihood ratio test.</p>
</div>
<div style="margin-bottom:50px;">
<p>So we now extend our model by both first-order interactions and call <code>add1</code> again with the extended model to test the remaining second-order interactions:</p>
</div>
<div style="margin-bottom:50px;">
<pre class="r"><code>glm.x1 &lt;- update ( glm.x0, . ~ . + species:season + species:mound )

add1( glm.x1, scope = ~ species*season*mound, test = &quot;Chisq&quot;)</code></pre>
<pre><code>## Single term additions
## 
## Model:
## count ~ species + season + mound + season:mound + species:season + 
##     species:mound
##                      Df Deviance    AIC    LRT Pr(&gt;Chi)
## &lt;none&gt;                    2.7898 87.073                
## species:season:mound  4   0.0000 92.284 2.7898   0.5936</code></pre>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
